/**
 * SamlSettingsPanel — admin UI for configuring SAML SSO. Only renders when
 * the current user has the 'manage_admin_settings' feature (server-side
 * enforced too). The SP's own signing keypair is auto-generated by the
 * backend on first use (see saml_service.py) — nothing to configure here
 * beyond the IdP's own details and, optionally, which group new SSO users
 * land in.
 */
import { useEffect, useState } from "react";
import { API_BASE, apiGet, apiPut, ApiError } from "../api/client";
import type { AdminSettings, Group } from "../types";

export function SamlSettingsPanel() {
  const [settings, setSettings] = useState<AdminSettings | null>(null);
  const [groups, setGroups] = useState<Group[]>([]);
  const [enabled, setEnabled] = useState(false);
  const [entityId, setEntityId] = useState("");
  const [ssoUrl, setSsoUrl] = useState("");
  const [cert, setCert] = useState("");
  const [defaultGroupId, setDefaultGroupId] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [busy, setBusy] = useState(false);

  const load = () => {
    setLoadError(null);
    Promise.all([apiGet<AdminSettings>("/admin/settings"), apiGet<Group[]>("/groups")])
      .then(([s, g]) => {
        setSettings(s);
        setGroups(g);
        setEnabled(s.saml_enabled);
        setEntityId(s.saml_idp_entity_id);
        setSsoUrl(s.saml_idp_sso_url);
        setDefaultGroupId(s.saml_default_group_id);
      })
      .catch((err) => setLoadError(err instanceof ApiError ? err.message : "Couldn't load SSO settings."));
  };

  useEffect(load, []);

  const save = async (e: React.FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    setSaved(false);
    try {
      const updated = await apiPut<AdminSettings>("/admin/settings", {
        saml_enabled: enabled,
        saml_idp_entity_id: entityId || undefined,
        saml_idp_sso_url: ssoUrl || undefined,
        saml_idp_x509_cert: cert || undefined,
        saml_default_group_id: defaultGroupId || undefined,
      });
      setSettings(updated);
      setCert("");
      setSaved(true);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Couldn't save SSO settings.");
    } finally {
      setBusy(false);
    }
  };

  if (loadError) {
    return (
      <div className="settings-tab-pane">
        <div className="auth-error">
          {loadError}
          <button type="button" className="link-btn" style={{ marginLeft: 8 }} onClick={load}>Retry</button>
        </div>
      </div>
    );
  }
  if (!settings) {
    return <div className="settings-tab-pane"><p className="muted">Loading…</p></div>;
  }

  return (
    <div className="settings-tab-pane">
      <p className="admin-settings-banner">
        Register this app as a SAML Service Provider in your Identity Provider (Okta, Azure AD, OneLogin, …), then
        paste the IdP's own details below. The first successful SSO login for a given email auto-creates a local
        account for it — optionally into the default group below — so nobody needs to be pre-created by hand.
      </p>

      <div style={{ background: "var(--surface)", padding: 16, borderRadius: 8, marginBottom: 16, border: "1px solid var(--border)" }}>
        <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 6 }}>This app's own SP details (hand these to your IdP)</div>
        <label style={{ display: "block", fontSize: 12, marginBottom: 6 }}>
          Entity ID
          <div className="muted" style={{ fontFamily: "monospace", fontSize: 12 }}>{settings.saml_sp_entity_id}</div>
        </label>
        <a
          href={`${API_BASE}/saml/metadata`}
          target="_blank"
          rel="noreferrer"
          className="link-btn"
          style={{ fontSize: 12 }}
        >
          Download SP metadata XML
        </a>
      </div>

      <form className="auth-form admin-settings-form" onSubmit={save}>
        <fieldset className="admin-fieldset">
          <legend>Identity Provider</legend>
          <label style={{ display: "flex", flexDirection: "row", alignItems: "center", gap: 6, cursor: "pointer" }}>
            <input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />
            Enable SAML SSO login
          </label>
          <label>
            IdP entity ID
            <input value={entityId} onChange={(e) => setEntityId(e.target.value)} placeholder="https://idp.example.com/metadata" />
          </label>
          <label>
            IdP SSO URL
            <input value={ssoUrl} onChange={(e) => setSsoUrl(e.target.value)} placeholder="https://idp.example.com/sso" />
          </label>
          <label>
            IdP signing certificate (PEM)
            <textarea
              className="text-dialog-input"
              rows={5}
              value={cert}
              onChange={(e) => setCert(e.target.value)}
              placeholder={settings.saml_idp_x509_cert_set ? "•••••••• (set — leave blank to keep)" : "-----BEGIN CERTIFICATE-----..."}
              style={{ fontFamily: "monospace", fontSize: 11 }}
            />
          </label>
          <label>
            Default group for new SSO users (optional)
            <select value={defaultGroupId} onChange={(e) => setDefaultGroupId(e.target.value)}>
              <option value="">None — admin assigns manually</option>
              {groups.map((g) => (
                <option key={g.id} value={g.id}>{g.name}</option>
              ))}
            </select>
          </label>
        </fieldset>

        {error && <div className="auth-error">{error}</div>}
        {saved && <div className="auth-success">Saved.</div>}
        <button type="submit" disabled={busy}>
          {busy ? "Saving..." : "Save"}
        </button>
      </form>
    </div>
  );
}
